version: "3.8"

services:
  client:
    build: ./CLIENT
    user: node
    entrypoint: sh -c
    working_dir: /home/node
    command: '"npm install && npm run dev"'
    ports:
      - 5173:5173
    volumes:
      - ./client:/home/node

  server:
    build: ./SERVER
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    ports:
      - 8080:80
    volumes:
      - ./server:/home/node
