services:
  SERVER:
    image: node:latest
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:password@mongo:27017/app?authSource=admin
      DATABASE_URL: postgres://techshop_site:3zH659q0fUMW6ve4FXLv@postgres:5432/techshop
      JWT_SECRET: 'codeSecretJWTTechshop'
    ports:
      - 3000:3000
    working_dir: /home/node/app
    volumes:
      - ./SERVER:/home/node/app
    command: sh -c "npm install && npm run dev_nodemon"

  mongo:
    image: mongo:latest
    ports:
      - 127.0.0.1:27018:27017
    volumes:
      - db-data:/data/db
      - ./mongo/data:/home/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    working_dir: /home/data

  postgres:
    image: postgres:latest
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=techshop_site
      - POSTGRES_PASSWORD=3zH659q0fUMW6ve4FXLv
      - POSTGRES_DB=techshop
    volumes:
      - pg-data:/var/lib/postgresql/data

  CLIENT:
    image: node
    build:
      context: ./CLIENT
    ports:
      - 8080:8080
    working_dir: /home/app/
    environment:
      NODE_ENV: development
    volumes:
      - ./CLIENT:/home/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - SERVER

volumes:
  db-data: {}
  pg-data: {}
