#Ceci est une version TEST ne pas la changer Kilyan s'en occupe

version: "3.8"

services:
  client:
    build: ./CLIENT
    user: node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    ports:
      - 5173:5173
    volumes:
      - ./client:/app

  server:
    build: ./SERVER
    user: node
    tty: true
    stdin_open: true
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    ports:
      - 8080:80
    volumes:
      - ./server:/app
